// File generated by FlutterFire CLI for agrichain-ai-hackathon.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9X_RxuZLXR5wnfXq-ty7hEJZy6IZhDKI',
    appId: '1:332991210562:web:9ef5efc5c7995dc839b9db',
    messagingSenderId: '332991210562',
    projectId: 'agrichain-ai-hackathon',
    authDomain: 'agrichain-ai-hackathon.firebaseapp.com',
    storageBucket: 'agrichain-ai-hackathon.firebasestorage.app',
    databaseURL: 'https://agrichain-ai-hackathon-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3lJ8o9kphfuTpOkuf-Wyh7nZQw3dNeiY',
    appId: '1:332991210562:android:d9d65cce40757e0e39b9db',
    messagingSenderId: '332991210562',
    projectId: 'agrichain-ai-hackathon',
    storageBucket: 'agrichain-ai-hackathon.firebasestorage.app',
    databaseURL: 'https://agrichain-ai-hackathon-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9X_RxuZLXR5wnfXq-ty7hEJZy6IZhDKI',
    appId: '1:332991210562:ios:1a2b3c4d5e6f7a8b',
    messagingSenderId: '332991210562',
    projectId: 'agrichain-ai-hackathon',
    storageBucket: 'agrichain-ai-hackathon.firebasestorage.app',
    iosBundleId: 'com.agrichain.mobile',
    databaseURL: 'https://agrichain-ai-hackathon-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9X_RxuZLXR5wnfXq-ty7hEJZy6IZhDKI',
    appId: '1:332991210562:ios:1a2b3c4d5e6f7a8b',
    messagingSenderId: '332991210562',
    projectId: 'agrichain-ai-hackathon',
    storageBucket: 'agrichain-ai-hackathon.firebasestorage.app',
    iosBundleId: 'com.agrichain.mobile',
    databaseURL: 'https://agrichain-ai-hackathon-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9X_RxuZLXR5wnfXq-ty7hEJZy6IZhDKI',
    appId: '1:332991210562:web:334d34986753c77439b9db',
    messagingSenderId: '332991210562',
    projectId: 'agrichain-ai-hackathon',
    authDomain: 'agrichain-ai-hackathon.firebaseapp.com',
    storageBucket: 'agrichain-ai-hackathon.firebasestorage.app',
    databaseURL: 'https://agrichain-ai-hackathon-default-rtdb.firebaseio.com',
  );
}
